package com.meridian.service;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.meridian.domain.*;
import com.meridian.payment.*;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.support.TransactionTemplate;
import org.springframework.web.server.ResponseStatusException;
import javax.crypto.Mac;
import javax.crypto.spec.SecretKeySpec;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.time.Instant;
import java.util.*;
import java.util.function.Supplier;

/** Single-instance synthetic ledger. One monitor is held until every transaction commits. */
@Service
public class RehearsalBank {
  public record Payment(String recipientId, Long amountMinor, String method, String note, String scenario) {}
  public record IntentRequest(String recipientId, Long amountMinor, String method, String corridor, String note, String scenario) {}
  public record Limit(String category, Long limitMinor) {}
  public record Callback(String sessionId, String eventId, String paymentId, String status) {}
  private record Intent(String id, String room, String key, String payload, String status, String provider, long amount) {}
  private record Stored(Payment payment, String corridor) {}
  private final JdbcTemplate db;
  private final TransactionTemplate tx;
  private final ObjectMapper json;
  private final FixtureService fixture;
  private final Map<String, PaymentProvider> providers;
  private final PaymentFlowCatalog catalog;
  private final ReturnStateSigner returnState;
  private final String webhookSecret;

  public RehearsalBank(JdbcTemplate db, TransactionTemplate tx, ObjectMapper json, FixtureService fixture,
    List<PaymentProvider> providers, PaymentFlowCatalog catalog, ReturnStateSigner returnState,
    @Value("${meridian.webhook.secret:}") String secret) {
    this.db=db; this.tx=tx; this.json=json; this.fixture=fixture; this.catalog=catalog; this.returnState=returnState; this.webhookSecret=secret;
    this.providers=new HashMap<>(); providers.forEach(p -> this.providers.put(p.getProviderId(),p));
    db.execute("CREATE TABLE IF NOT EXISTS meridian_rooms (room VARCHAR(64) PRIMARY KEY, state_json CLOB NOT NULL)");
    db.execute("CREATE TABLE IF NOT EXISTS meridian_intents (payment_id VARCHAR(64) PRIMARY KEY, room VARCHAR(64) NOT NULL, client_key VARCHAR(100) NOT NULL, payload CLOB NOT NULL, phase VARCHAR(20) NOT NULL, provider VARCHAR(20) NOT NULL, amount BIGINT NOT NULL, UNIQUE(room,client_key))");
    db.execute("CREATE TABLE IF NOT EXISTS meridian_callbacks (room VARCHAR(64), provider VARCHAR(20), event_id VARCHAR(100), payload_hash VARCHAR(64) NOT NULL, PRIMARY KEY(room,provider,event_id))");
    db.execute("CREATE TABLE IF NOT EXISTS meridian_audit (sequence BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, room VARCHAR(64), event_json CLOB)");
  }
  private <T> T atomic(Supplier<T> action) { return tx.execute(s -> action.get()); }
  public static void check(boolean valid, String message) { if(!valid) throw new ResponseStatusException(HttpStatus.BAD_REQUEST,message); }
  private void room(String value) { check(value!=null && value.matches("[A-Za-z0-9_-]{3,64}"),"Invalid rehearsal session"); }
  private String encode(Object value) { try { return json.writeValueAsString(value); } catch(Exception e) { throw new IllegalStateException(e); } }
  private <T> T decode(String value, Class<T> type) { try { return json.readValue(value,type); } catch(Exception e) { throw new IllegalStateException(e); } }
  private BankState read(String room) {
    var found=db.query("SELECT state_json FROM meridian_rooms WHERE room=?",(r,n)->r.getString(1),room);
    if(found.isEmpty()) { var state=fixture.loadInitialState(); db.update("INSERT INTO meridian_rooms(room,state_json) VALUES(?,?)",room,encode(state)); return state; }
    return decode(found.getFirst(),BankState.class);
  }
  private void save(String room,BankState state) { db.update("UPDATE meridian_rooms SET state_json=? WHERE room=?",encode(state),room); }
  private void audit(String room,String type,String id,String provider) { db.update("INSERT INTO meridian_audit(room,event_json) VALUES(?,?)",room,encode(Map.of("type",type,"paymentId",id,"provider",provider,"timestamp",Instant.now().toString()))); }
  public synchronized BankState state(String room) { room(room); return atomic(()->read(room)); }
  public synchronized Map<String,Object> reset(String room) { room(room); return atomic(()->{
    db.update("DELETE FROM meridian_callbacks WHERE room=?",room); db.update("DELETE FROM meridian_intents WHERE room=?",room); db.update("DELETE FROM meridian_audit WHERE room=?",room); db.update("DELETE FROM meridian_rooms WHERE room=?",room);
    return Map.of("ok",true,"state",read(room));
  }); }
  public synchronized Map<String,Object> budget(String room,Limit limit) { room(room); check(limit!=null && limit.limitMinor()!=null && limit.limitMinor()>0 && limit.limitMinor()<=1000000,"Invalid budget limit"); return atomic(()->{
    var state=read(room); var budget=state.getBudgets().stream().filter(b->b.getCategory().equals(limit.category())).findFirst().orElseThrow(()->new ResponseStatusException(HttpStatus.BAD_REQUEST,"Unknown category"));
    budget.setLimit(limit.limitMinor()); save(room,state); audit(room,"budget.updated","",""); return Map.of("ok",true,"state",state);
  }); }
  public synchronized Map<String,Object> events(String room) { room(room); return Map.of("events",db.query("SELECT event_json FROM meridian_audit WHERE room=? ORDER BY sequence DESC LIMIT 100",(r,n)->decode(r.getString(1),Map.class),room)); }
  private List<Intent> intents(String sql,Object...args) { return db.query(sql,(r,n)->new Intent(r.getString("payment_id"),r.getString("room"),r.getString("client_key"),r.getString("payload"),r.getString("phase"),r.getString("provider"),r.getLong("amount")),args); }
  private Payment normalize(Payment p) {
    check(p!=null && p.amountMinor()!=null && p.amountMinor()>=1 && p.amountMinor()<=1000000,"Amount must be integer pence from 1 to 1000000");
    check("card".equals(p.method()) || "bank".equals(p.method()),"Unknown payment method");
    check(fixture.getRecipient(p.recipientId())!=null,"Unknown recipient");
    check(p.note()==null || p.note().length()<=200,"Reference exceeds 200 characters");
    String scenario=p.scenario()==null?"success":p.scenario();
    check(Set.of("success","declined","unavailable","pending").contains(scenario),"Unknown simulation scenario");
    return new Payment(p.recipientId(),p.amountMinor(),p.method(),p.note()==null?"":p.note(),scenario);
  }
  private String payload(Payment p,String corridor,boolean v2) {
    return v2 ? encode(List.of(p.recipientId(),p.amountMinor(),p.method(),p.note(),corridor,"v2"))
      : encode(List.of(p.recipientId(),p.amountMinor(),p.method(),p.note()));
  }
  private Stored stored(Intent intent) {
    var tuple=decode(intent.payload(),List.class);
    String corridor=tuple.size()>=5?String.valueOf(tuple.get(4)):"UK";
    var payment=new Payment((String)tuple.get(0),((Number)tuple.get(1)).longValue(),(String)tuple.get(2),(String)tuple.get(3),"success");
    return new Stored(payment,corridor);
  }
  private long reserved(String room) { Long value=db.queryForObject("SELECT COALESCE(SUM(amount),0) FROM meridian_intents WHERE room=? AND phase IN ('submitting','pending')",Long.class,room); return value==null?0:value; }
  private Intent prepare(String room,String key,Payment p,String corridor,String provider,boolean v2) {
    var state=read(room); var body=payload(p,corridor,v2); var rows=intents("SELECT * FROM meridian_intents WHERE room=? AND client_key=?",room,key);
    if(!rows.isEmpty()) {
      var old=rows.getFirst();
      if(!old.payload().equals(body)) throw new ResponseStatusException(HttpStatus.CONFLICT,"Idempotency key belongs to a different payment");
      if(Set.of("completed","pending","submitting","declined-final").contains(old.status())) return old;
      if(state.getBalance()-reserved(room)<p.amountMinor()) throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Insufficient available balance");
      db.update("UPDATE meridian_intents SET phase='submitting' WHERE payment_id=?",old.id());
      return new Intent(old.id(),room,key,old.payload(),"prepared",old.provider(),old.amount());
    }
    if(state.getBalance()-reserved(room)<p.amountMinor()) throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Insufficient available balance");
    String id=UUID.randomUUID().toString();
    db.update("INSERT INTO meridian_intents(payment_id,room,client_key,payload,phase,provider,amount) VALUES(?,?,?,?,?,?,?)",id,room,key,body,"submitting",provider,p.amountMinor());
    audit(room,"payment.prepared",id,provider);
    return new Intent(id,room,key,body,"prepared",provider,p.amountMinor());
  }
  private Map<String,Object> pending(String id) { return Map.of("ok",false,"error","Payment pending confirmation. Do not create another payment.","code","PAYMENT_PENDING","paymentId",id); }
  private Map<String,Object> completed(Intent intent) {
    var state=read(intent.room()); var txn=state.getTransactions().stream().filter(t->t.getId().equals(intent.id())).findFirst().orElseThrow();
    return Map.of("ok",true,"state",state,"transaction",txn);
  }
  private Map<String,Object> fail(String code,String message) { return Map.of("ok",false,"code",code,"error",message); }
  private Transaction debit(Intent intent,Payment p) {
    var state=read(intent.room()); check(state.getBalance()>=intent.amount(),"Insufficient balance for settlement");
    var recipient=fixture.getRecipient(p.recipientId());
    var transaction=new Transaction(intent.id(),"MER-"+intent.id().substring(0,8).toUpperCase(),p.recipientId(),recipient.getName(),recipient.getCategory(),intent.amount(),fixture.getDemoDate(),intent.provider(),p.method(),"completed",p.note());
    state.setBalance(state.getBalance()-intent.amount()); state.getTransactions().add(transaction); save(intent.room(),state);
    db.update("UPDATE meridian_intents SET phase='completed' WHERE payment_id=?",intent.id()); audit(intent.room(),"payment.completed",intent.id(),intent.provider()); return transaction;
  }
  public synchronized Map<String,Object> payment(String room,String key,Payment input) {
    room(room); check(key!=null && key.matches("[A-Za-z0-9_-]{1,100}"),"Invalid Idempotency-Key"); var p=normalize(input);
    var resolution=catalog.resolve(p.method(),"UK");
    return execute(room,key,p,resolution.corridor(),resolution.provider(),false);
  }
  public synchronized Map<String,Object> createIntent(String room,String key,IntentRequest input) {
    room(room); check(key!=null && key.matches("[A-Za-z0-9_-]{1,100}"),"Invalid Idempotency-Key");
    check(input!=null && input.corridor()!=null && !input.corridor().isBlank(),"Corridor is required");
    var resolution=catalog.resolve(input.method(),input.corridor());
    var p=normalize(new Payment(input.recipientId(),input.amountMinor(),input.method(),input.note(),input.scenario()));
    return execute(room,key,p,resolution.corridor(),resolution.provider(),true);
  }
  public synchronized Map<String,Object> readIntent(String room,String id) {
    room(room); check(id!=null && id.matches("[A-Za-z0-9-]{1,64}"),"Invalid payment intent id");
    return atomic(()->{
      var rows=intents("SELECT * FROM meridian_intents WHERE payment_id=? AND room=?",id,room);
      if(rows.isEmpty()) throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Unknown payment intent");
      return view(rows.getFirst());
    });
  }
  private Map<String,Object> execute(String room,String key,Payment p,String corridor,String provider,boolean v2) {
    // Commit intent before sending to a provider. Keep the same monitor across both commits.
    Intent intent=atomic(()->prepare(room,key,p,corridor,provider,v2));
    if(intent.status().equals("completed")) return atomic(()->v2?view(intent):completed(intent));
    if(Set.of("pending","submitting").contains(intent.status())) return v2?atomic(()->view(intent)):pending(intent.id());
    if(intent.status().equals("declined-final")) return v2?atomic(()->view(intent)):fail("PAYMENT_DECLINED","Payment was declined by reconciliation");
    PaymentProvider.Outcome outcome;
    try { outcome=providers.get(intent.provider()).authorize(intent.id(),p.scenario(),corridor); }
    catch(RuntimeException e) { outcome=PaymentProvider.Outcome.PENDING; }
    final var result=outcome;
    return atomic(()->{
      if(result==PaymentProvider.Outcome.SUCCESS) { debit(intent,p); return v2?view(reload(intent.id())):completed(intent); }
      String phase=result==PaymentProvider.Outcome.PENDING?"pending":result==PaymentProvider.Outcome.DECLINED?"declined":"unavailable";
      db.update("UPDATE meridian_intents SET phase=? WHERE payment_id=?",phase,intent.id()); audit(room,"payment."+phase,intent.id(),intent.provider());
      if(v2) return view(reload(intent.id()));
      if(result==PaymentProvider.Outcome.PENDING) return pending(intent.id());
      return fail(result==PaymentProvider.Outcome.DECLINED?"PAYMENT_DECLINED":"PROVIDER_UNAVAILABLE",result==PaymentProvider.Outcome.DECLINED?"Payment declined. No debit was made.":"Provider unavailable before authorization. No debit was made.");
    });
  }
  private Intent reload(String id) { return intents("SELECT * FROM meridian_intents WHERE payment_id=?",id).getFirst(); }
  private String lifecycle(String phase) {
    return switch(phase) {
      case "completed" -> "succeeded";
      case "pending" -> "pending_confirmation";
      case "declined","declined-final" -> "declined";
      case "unavailable" -> "unavailable";
      default -> "processing";
    };
  }
  private Map<String,Object> view(Intent intent) {
    var stored=stored(intent); String status=lifecycle(intent.status()); var state=read(intent.room());
    Transaction txn="succeeded".equals(status)?state.getTransactions().stream().filter(t->t.getId().equals(intent.id())).findFirst().orElseThrow():null;
    var resolution=catalog.resolve(stored.payment().method(),stored.corridor());
    var body=new LinkedHashMap<String,Object>();
    body.put("ok","succeeded".equals(status));
    body.put("code",switch(status) { case "succeeded"->"PAYMENT_SUCCEEDED"; case "declined"->"PAYMENT_DECLINED"; case "unavailable"->"PROVIDER_UNAVAILABLE"; default->"PAYMENT_PENDING"; });
    if(!"succeeded".equals(status)) body.put("error",switch(intent.status()) {
      case "declined-final"->"Payment was declined by reconciliation";
      case "declined"->"Payment declined. No debit was made.";
      case "unavailable"->"Provider unavailable before authorization. No debit was made.";
      default->"Payment pending confirmation. Do not create another payment.";
    });
    body.put("id",intent.id()); body.put("status",status); body.put("authoritative",true);
    body.put("amountMinor",intent.amount()); body.put("currency",catalog.currency());
    body.put("method",stored.payment().method()); body.put("corridor",stored.corridor());
    body.put("recipientId",stored.payment().recipientId()); body.put("note",stored.payment().note());
    body.put("resolution",Map.of("flow",resolution.flow(),"provider",intent.provider()));
    body.put("action",action(status,intent,txn));
    body.put("returnState",returnState.sign(intent.id(),status,intent.amount()));
    body.put("state",state);
    if(txn!=null) body.put("transaction",txn);
    return body;
  }
  private Map<String,Object> action(String status,Intent intent,Transaction txn) {
    return switch(status) {
      case "succeeded" -> Map.of("type","complete","payload",Map.of("transactionId",txn.getId(),"reference",txn.getReference(),"retryable",false));
      case "declined" -> Map.of("type","terminal","payload",Map.of("code","PAYMENT_DECLINED","final","declined-final".equals(intent.status()),"retryable",false));
      case "unavailable" -> Map.of("type","retry","payload",Map.of("code","PROVIDER_UNAVAILABLE","retryable",true,"sameIdempotencyKey",true));
      case "processing" -> Map.of("type","await_confirmation","payload",Map.of("paymentId",intent.id(),"retryable",false,"instruction","Payment is still processing. Do not create another payment."));
      default -> Map.of("type","await_confirmation","payload",Map.of("paymentId",intent.id(),"retryable",false,"instruction","Do not create another payment."));
    };
  }
  public synchronized Map<String,Object> webhook(String provider,String timestamp,String signature,String raw) {
    if(webhookSecret.isBlank()) throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Webhook simulation is disabled");
    try {
      long sent=Long.parseLong(timestamp); long now=Instant.now().getEpochSecond();
      if(sent<now-300 || sent>now+300 || signature==null || !signature.matches("[0-9a-f]{64}")) throw new IllegalArgumentException();
      Mac hmac=Mac.getInstance("HmacSHA256"); hmac.init(new SecretKeySpec(webhookSecret.getBytes(StandardCharsets.UTF_8),"HmacSHA256"));
      if(!MessageDigest.isEqual(hmac.doFinal((timestamp+"."+raw).getBytes(StandardCharsets.UTF_8)),HexFormat.of().parseHex(signature))) throw new IllegalArgumentException();
    } catch(Exception e) { throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Invalid webhook signature or timestamp"); }
    Callback event;
    try { event=json.readValue(raw,Callback.class); } catch(Exception e) { throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Invalid callback body"); }
    room(event.sessionId()); check(providers.containsKey(provider),"Unknown provider");
    check(event.eventId()!=null && event.eventId().matches("[A-Za-z0-9_-]{1,100}"),"Invalid event ID");
    check("completed".equals(event.status()) || "declined".equals(event.status()),"Invalid callback status");
    return atomic(()->{
      String hash;
      try { hash=HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(encode(event).getBytes(StandardCharsets.UTF_8))); } catch(Exception e) { throw new IllegalStateException(e); }
      var seen=db.query("SELECT payload_hash FROM meridian_callbacks WHERE room=? AND provider=? AND event_id=?",(r,n)->r.getString(1),event.sessionId(),provider,event.eventId());
      if(!seen.isEmpty()) { if(!hash.equals(seen.getFirst())) throw new ResponseStatusException(HttpStatus.CONFLICT,"Event ID payload changed"); return Map.of("ok",true,"duplicate",true); }
      var rows=intents("SELECT * FROM meridian_intents WHERE payment_id=? AND room=?",event.paymentId(),event.sessionId());
      check(!rows.isEmpty(),"Unknown payment intent"); var intent=rows.getFirst(); check(intent.provider().equals(provider),"Callback provider mismatch");
      if(!Set.of("pending","submitting").contains(intent.status())) throw new ResponseStatusException(HttpStatus.CONFLICT,"Payment already has a final outcome");
      if(event.status().equals("completed")) {
        var tuple=decode(intent.payload(),List.class); var p=new Payment((String)tuple.get(0),((Number)tuple.get(1)).longValue(),(String)tuple.get(2),(String)tuple.get(3),"success"); debit(intent,p);
      } else { db.update("UPDATE meridian_intents SET phase='declined-final' WHERE payment_id=?",intent.id()); audit(intent.room(),"payment.declined",intent.id(),provider); }
      db.update("INSERT INTO meridian_callbacks(room,provider,event_id,payload_hash) VALUES(?,?,?,?)",event.sessionId(),provider,event.eventId(),hash);
      return Map.of("ok",true,"duplicate",false);
    });
  }
}
