package com.meridian.service;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.meridian.domain.*;
import com.meridian.payment.*;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.support.TransactionTemplate;
import org.springframework.web.server.ResponseStatusException;
import javax.crypto.Mac;
import javax.crypto.spec.SecretKeySpec;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.time.Instant;
import java.util.*;
import java.util.function.Supplier;

/** Single-instance synthetic ledger. One monitor is held until every transaction commits. */
@Service
public class RehearsalBank {
  public record Payment(String recipientId, Long amountMinor, String method, String note, String scenario) {}
  public record Limit(String category, Long limitMinor) {}
  public record Callback(String sessionId, String eventId, String paymentId, String status) {}
  public record Authorization(String recipientId, Long amountMinor, String method, String note, String corridor, String scenario, String scaToken) {}
  private record Intent(String id, String room, String key, String payload, String status, String provider, long amount) {}
  private record AuthRow(String id, String room, String key, String payload, String phase, String provider, long amount,
    String corridor, String traceId, String declineClass, String providerCode, boolean failoverEligible, String resultCode) {}
  private record PreparedAuth(AuthRow row, boolean replay) {}
  private final JdbcTemplate db;
  private final TransactionTemplate tx;
  private final ObjectMapper json;
  private final FixtureService fixture;
  private final Map<String, PaymentProvider> providers;
  private final String webhookSecret;

  public RehearsalBank(JdbcTemplate db, TransactionTemplate tx, ObjectMapper json, FixtureService fixture,
    List<PaymentProvider> providers, @Value("${meridian.webhook.secret:}") String secret) {
    this.db=db; this.tx=tx; this.json=json; this.fixture=fixture; this.webhookSecret=secret;
    this.providers=new HashMap<>(); providers.forEach(p -> this.providers.put(p.getProviderId(),p));
    db.execute("CREATE TABLE IF NOT EXISTS meridian_rooms (room VARCHAR(64) PRIMARY KEY, state_json CLOB NOT NULL)");
    db.execute("CREATE TABLE IF NOT EXISTS meridian_intents (payment_id VARCHAR(64) PRIMARY KEY, room VARCHAR(64) NOT NULL, client_key VARCHAR(100) NOT NULL, payload CLOB NOT NULL, phase VARCHAR(20) NOT NULL, provider VARCHAR(20) NOT NULL, amount BIGINT NOT NULL, UNIQUE(room,client_key))");
    db.execute("CREATE TABLE IF NOT EXISTS meridian_callbacks (room VARCHAR(64), provider VARCHAR(20), event_id VARCHAR(100), payload_hash VARCHAR(64) NOT NULL, PRIMARY KEY(room,provider,event_id))");
    db.execute("CREATE TABLE IF NOT EXISTS meridian_audit (sequence BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, room VARCHAR(64), event_json CLOB)");
    db.execute("CREATE TABLE IF NOT EXISTS meridian_authorizations (payment_id VARCHAR(64) PRIMARY KEY, room VARCHAR(64) NOT NULL, client_key VARCHAR(100) NOT NULL, payload CLOB NOT NULL, phase VARCHAR(20) NOT NULL, provider VARCHAR(20) NOT NULL, amount BIGINT NOT NULL, corridor VARCHAR(8) NOT NULL, trace_id VARCHAR(64) NOT NULL, decline_class VARCHAR(10), provider_code VARCHAR(40), failover_eligible VARCHAR(5), result_code VARCHAR(40), UNIQUE(room, client_key))");
  }
  private <T> T atomic(Supplier<T> action) { return tx.execute(s -> action.get()); }
  public static void check(boolean valid, String message) { if(!valid) throw new ResponseStatusException(HttpStatus.BAD_REQUEST,message); }
  private void room(String value) { check(value!=null && value.matches("[A-Za-z0-9_-]{3,64}"),"Invalid rehearsal session"); }
  private String encode(Object value) { try { return json.writeValueAsString(value); } catch(Exception e) { throw new IllegalStateException(e); } }
  private <T> T decode(String value, Class<T> type) { try { return json.readValue(value,type); } catch(Exception e) { throw new IllegalStateException(e); } }
  private BankState read(String room) {
    var found=db.query("SELECT state_json FROM meridian_rooms WHERE room=?",(r,n)->r.getString(1),room);
    if(found.isEmpty()) { var state=fixture.loadInitialState(); db.update("INSERT INTO meridian_rooms(room,state_json) VALUES(?,?)",room,encode(state)); return state; }
    return decode(found.getFirst(),BankState.class);
  }
  private void save(String room,BankState state) { db.update("UPDATE meridian_rooms SET state_json=? WHERE room=?",encode(state),room); }
  private void audit(String room,String type,String id,String provider) { db.update("INSERT INTO meridian_audit(room,event_json) VALUES(?,?)",room,encode(Map.of("type",type,"paymentId",id,"provider",provider,"timestamp",Instant.now().toString()))); }
  private void auditAuth(String room, String type, String id, String provider, String traceId, Map<String, ?> extra) {
    var event = new LinkedHashMap<String, Object>();
    event.put("type", type);
    event.put("paymentId", id);
    event.put("provider", provider);
    event.put("timestamp", Instant.now().toString());
    event.put("traceId", traceId);
    extra.forEach(event::put);
    db.update("INSERT INTO meridian_audit(room,event_json) VALUES(?,?)", room, encode(event));
  }
  public synchronized BankState state(String room) { room(room); return atomic(()->read(room)); }
  public synchronized Map<String,Object> reset(String room) { room(room); return atomic(()->{
    db.update("DELETE FROM meridian_callbacks WHERE room=?",room); db.update("DELETE FROM meridian_intents WHERE room=?",room); db.update("DELETE FROM meridian_authorizations WHERE room=?",room); db.update("DELETE FROM meridian_audit WHERE room=?",room); db.update("DELETE FROM meridian_rooms WHERE room=?",room);
    return Map.of("ok",true,"state",read(room));
  }); }
  public synchronized Map<String,Object> budget(String room,Limit limit) { room(room); check(limit!=null && limit.limitMinor()!=null && limit.limitMinor()>0 && limit.limitMinor()<=1000000,"Invalid budget limit"); return atomic(()->{
    var state=read(room); var budget=state.getBudgets().stream().filter(b->b.getCategory().equals(limit.category())).findFirst().orElseThrow(()->new ResponseStatusException(HttpStatus.BAD_REQUEST,"Unknown category"));
    budget.setLimit(limit.limitMinor()); save(room,state); audit(room,"budget.updated","",""); return Map.of("ok",true,"state",state);
  }); }
  public synchronized Map<String,Object> events(String room) { room(room); return Map.of("events",db.query("SELECT event_json FROM meridian_audit WHERE room=? ORDER BY sequence DESC LIMIT 100",(r,n)->decode(r.getString(1),Map.class),room)); }
  private List<Intent> intents(String sql,Object...args) { return db.query(sql,(r,n)->new Intent(r.getString("payment_id"),r.getString("room"),r.getString("client_key"),r.getString("payload"),r.getString("phase"),r.getString("provider"),r.getLong("amount")),args); }
  private Payment normalize(Payment p) {
    check(p!=null && p.amountMinor()!=null && p.amountMinor()>=1 && p.amountMinor()<=1000000,"Amount must be integer pence from 1 to 1000000");
    check("card".equals(p.method()) || "bank".equals(p.method()),"Unknown payment method");
    check(fixture.getRecipient(p.recipientId())!=null,"Unknown recipient");
    check(p.note()==null || p.note().length()<=200,"Reference exceeds 200 characters");
    String scenario=p.scenario()==null?"success":p.scenario();
    check(Set.of("success","declined","unavailable","pending").contains(scenario),"Unknown simulation scenario");
    return new Payment(p.recipientId(),p.amountMinor(),p.method(),p.note()==null?"":p.note(),scenario);
  }
  private String payload(Payment p) { return encode(List.of(p.recipientId(),p.amountMinor(),p.method(),p.note())); }
  private long reserved(String room) {
    Long intents=db.queryForObject("SELECT COALESCE(SUM(amount),0) FROM meridian_intents WHERE room=? AND phase IN ('submitting','pending')",Long.class,room);
    Long auths=db.queryForObject("SELECT COALESCE(SUM(amount),0) FROM meridian_authorizations WHERE room=? AND phase='PROCESSING'",Long.class,room);
    return (intents==null?0:intents)+(auths==null?0:auths);
  }
  private Intent prepare(String room,String key,Payment p) {
    var state=read(room); var rows=intents("SELECT * FROM meridian_intents WHERE room=? AND client_key=?",room,key);
    if(!rows.isEmpty()) {
      var old=rows.getFirst();
      if(!old.payload().equals(payload(p))) throw new ResponseStatusException(HttpStatus.CONFLICT,"Idempotency key belongs to a different payment");
      if(Set.of("completed","pending","submitting","declined-final").contains(old.status())) return old;
      if(state.getBalance()-reserved(room)<p.amountMinor()) throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Insufficient available balance");
      db.update("UPDATE meridian_intents SET phase='submitting' WHERE payment_id=?",old.id());
      return new Intent(old.id(),room,key,old.payload(),"prepared",old.provider(),old.amount());
    }
    if(state.getBalance()-reserved(room)<p.amountMinor()) throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Insufficient available balance");
    String id=UUID.randomUUID().toString(), provider=p.method().equals("card")?"adyen":"worldpay";
    db.update("INSERT INTO meridian_intents(payment_id,room,client_key,payload,phase,provider,amount) VALUES(?,?,?,?,?,?,?)",id,room,key,payload(p),"submitting",provider,p.amountMinor());
    audit(room,"payment.prepared",id,provider);
    return new Intent(id,room,key,payload(p),"prepared",provider,p.amountMinor());
  }
  private Map<String,Object> pending(String id) { return Map.of("ok",false,"error","Payment pending confirmation. Do not create another payment.","code","PAYMENT_PENDING","paymentId",id); }
  private Map<String,Object> completed(Intent intent) {
    var state=read(intent.room()); var txn=state.getTransactions().stream().filter(t->t.getId().equals(intent.id())).findFirst().orElseThrow();
    return Map.of("ok",true,"state",state,"transaction",txn);
  }
  private Map<String,Object> fail(String code,String message) { return Map.of("ok",false,"code",code,"error",message); }
  private Transaction appendCompleted(String room, String id, String provider, long amount, String recipientId, String method, String note) {
    var state=read(room); check(state.getBalance()>=amount,"Insufficient balance for settlement");
    var recipient=fixture.getRecipient(recipientId);
    var transaction=new Transaction(id,"MER-"+id.substring(0,8).toUpperCase(),recipientId,recipient.getName(),recipient.getCategory(),amount,fixture.getDemoDate(),provider,method,"completed",note);
    state.setBalance(state.getBalance()-amount); state.getTransactions().add(transaction); save(room,state); return transaction;
  }
  private Transaction debit(Intent intent,Payment p) {
    var transaction=appendCompleted(intent.room(),intent.id(),intent.provider(),intent.amount(),p.recipientId(),p.method(),p.note());
    db.update("UPDATE meridian_intents SET phase='completed' WHERE payment_id=?",intent.id()); audit(intent.room(),"payment.completed",intent.id(),intent.provider()); return transaction;
  }
  public synchronized Map<String,Object> payment(String room,String key,Payment input) {
    room(room); check(key!=null && key.matches("[A-Za-z0-9_-]{1,100}"),"Invalid Idempotency-Key"); var p=normalize(input);
    // Commit intent before sending to a provider. Keep the same monitor across both commits.
    Intent intent=atomic(()->prepare(room,key,p));
    if(intent.status().equals("completed")) return atomic(()->completed(intent));
    if(Set.of("pending","submitting").contains(intent.status())) return pending(intent.id());
    if(intent.status().equals("declined-final")) return fail("PAYMENT_DECLINED","Payment was declined by reconciliation");
    PaymentProvider.Outcome outcome;
    try { outcome=providers.get(intent.provider()).authorize(intent.id(),p.scenario(),"UK"); }
    catch(RuntimeException e) { outcome=PaymentProvider.Outcome.PENDING; }
    final var result=outcome;
    return atomic(()->{
      if(result==PaymentProvider.Outcome.SUCCESS) { debit(intent,p); return completed(intent); }
      String phase=result==PaymentProvider.Outcome.PENDING?"pending":result==PaymentProvider.Outcome.DECLINED?"declined":"unavailable";
      db.update("UPDATE meridian_intents SET phase=? WHERE payment_id=?",phase,intent.id()); audit(room,"payment."+phase,intent.id(),intent.provider());
      if(result==PaymentProvider.Outcome.PENDING) return pending(intent.id());
      return fail(result==PaymentProvider.Outcome.DECLINED?"PAYMENT_DECLINED":"PROVIDER_UNAVAILABLE",result==PaymentProvider.Outcome.DECLINED?"Payment declined. No debit was made.":"Provider unavailable before authorization. No debit was made.");
    });
  }
  public synchronized Map<String,Object> webhook(String provider,String timestamp,String signature,String raw) {
    if(webhookSecret.isBlank()) throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Webhook simulation is disabled");
    try {
      long sent=Long.parseLong(timestamp); long now=Instant.now().getEpochSecond();
      if(sent<now-300 || sent>now+300 || signature==null || !signature.matches("[0-9a-f]{64}")) throw new IllegalArgumentException();
      Mac hmac=Mac.getInstance("HmacSHA256"); hmac.init(new SecretKeySpec(webhookSecret.getBytes(StandardCharsets.UTF_8),"HmacSHA256"));
      if(!MessageDigest.isEqual(hmac.doFinal((timestamp+"."+raw).getBytes(StandardCharsets.UTF_8)),HexFormat.of().parseHex(signature))) throw new IllegalArgumentException();
    } catch(Exception e) { throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Invalid webhook signature or timestamp"); }
    Callback event;
    try { event=json.readValue(raw,Callback.class); } catch(Exception e) { throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Invalid callback body"); }
    room(event.sessionId()); check(providers.containsKey(provider),"Unknown provider");
    check(event.eventId()!=null && event.eventId().matches("[A-Za-z0-9_-]{1,100}"),"Invalid event ID");
    check("completed".equals(event.status()) || "declined".equals(event.status()),"Invalid callback status");
    return atomic(()->{
      String hash;
      try { hash=HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(encode(event).getBytes(StandardCharsets.UTF_8))); } catch(Exception e) { throw new IllegalStateException(e); }
      var seen=db.query("SELECT payload_hash FROM meridian_callbacks WHERE room=? AND provider=? AND event_id=?",(r,n)->r.getString(1),event.sessionId(),provider,event.eventId());
      if(!seen.isEmpty()) { if(!hash.equals(seen.getFirst())) throw new ResponseStatusException(HttpStatus.CONFLICT,"Event ID payload changed"); return Map.of("ok",true,"duplicate",true); }
      var rows=intents("SELECT * FROM meridian_intents WHERE payment_id=? AND room=?",event.paymentId(),event.sessionId());
      check(!rows.isEmpty(),"Unknown payment intent"); var intent=rows.getFirst(); check(intent.provider().equals(provider),"Callback provider mismatch");
      if(!Set.of("pending","submitting").contains(intent.status())) throw new ResponseStatusException(HttpStatus.CONFLICT,"Payment already has a final outcome");
      if(event.status().equals("completed")) {
        var tuple=decode(intent.payload(),List.class); var p=new Payment((String)tuple.get(0),((Number)tuple.get(1)).longValue(),(String)tuple.get(2),(String)tuple.get(3),"success"); debit(intent,p);
      } else { db.update("UPDATE meridian_intents SET phase='declined-final' WHERE payment_id=?",intent.id()); audit(intent.room(),"payment.declined",intent.id(),provider); }
      db.update("INSERT INTO meridian_callbacks(room,provider,event_id,payload_hash) VALUES(?,?,?,?)",event.sessionId(),provider,event.eventId(),hash);
      return Map.of("ok",true,"duplicate",false);
    });
  }
  public synchronized Map<String,Object> authorize(String room, String key, String traceHeader, Authorization input) {
    room(room);
    check(key!=null && key.matches("[A-Za-z0-9_-]{1,100}"),"Invalid Idempotency-Key");
    var request=normalizeAuth(input);
    String traceId=resolveTrace(traceHeader);
    var sca=ScaStepUp.verify(request.scaToken());
    if(sca.verdict()==ScaStepUp.Verdict.MALFORMED || sca.verdict()==ScaStepUp.Verdict.EXPIRED) {
      String type=sca.verdict()==ScaStepUp.Verdict.EXPIRED?"sca.expired":"sca.rejected";
      atomic(()->{ auditAuth(room,type,"","",traceId,sca.flow().isBlank()?Map.of():Map.of("flow",sca.flow())); return null; });
      String code=sca.verdict()==ScaStepUp.Verdict.EXPIRED?"SCA_TOKEN_EXPIRED":"INVALID_SCA_TOKEN";
      String error=sca.verdict()==ScaStepUp.Verdict.EXPIRED?"Step-up token is expired.":"Step-up token is invalid.";
      return scaRejected(code,error,traceId);
    }
    if(sca.verdict()==ScaStepUp.Verdict.CHALLENGE_FAILED) return atomic(()->failChallenge(room,key,request,traceId,sca.flow()));
    PreparedAuth prepared=atomic(()->prepareAuth(room,key,request,traceId,sca.flow()));
    if(prepared.replay()) return atomic(()->replayAuth(prepared.row()));
    SandboxAuthorization sandbox;
    try { sandbox=providers.get(prepared.row().provider()).authorizeSandbox(prepared.row().id(),request.scenario(),request.corridor()); }
    catch(RuntimeException ex) { sandbox=SandboxAuthorization.ambiguous(prepared.row().provider()); }
    SandboxAuthorization outcome=sandbox;
    return atomic(()->finishAuth(prepared.row(),request,outcome));
  }
  private Authorization normalizeAuth(Authorization p) {
    check(p!=null && p.amountMinor()!=null && p.amountMinor()>=1 && p.amountMinor()<=1000000,"Amount must be integer pence from 1 to 1000000");
    check("card".equals(p.method()) || "bank".equals(p.method()),"Unknown payment method");
    check(fixture.getRecipient(p.recipientId())!=null,"Unknown recipient");
    check(p.note()==null || p.note().length()<=200,"Reference exceeds 200 characters");
    check(p.corridor()!=null && ProviderRouter.route(p.corridor(),p.method())!=null,"Unknown corridor");
    String scenario=p.scenario()==null?"success":p.scenario();
    check(Set.of("success","soft_decline","hard_decline","ambiguous","unknown_code").contains(scenario),"Unknown simulation scenario");
    check(p.scaToken()!=null && !p.scaToken().isBlank(),"Step-up token is required");
    return new Authorization(p.recipientId(),p.amountMinor(),p.method(),p.note()==null?"":p.note(),p.corridor(),scenario,p.scaToken());
  }
  private String resolveTrace(String supplied) {
    if(supplied==null || supplied.isBlank()) return UUID.randomUUID().toString();
    check(supplied.matches("[A-Za-z0-9_-]{8,64}"),"Invalid X-Trace-Id");
    return supplied;
  }
  private String authPayload(Authorization p) { return encode(List.of(p.recipientId(),p.amountMinor(),p.method(),p.note(),p.corridor(),p.scaToken())); }
  private List<AuthRow> authRows(String sql, Object... args) {
    return db.query(sql,(r,n)->new AuthRow(r.getString("payment_id"),r.getString("room"),r.getString("client_key"),r.getString("payload"),r.getString("phase"),r.getString("provider"),r.getLong("amount"),r.getString("corridor"),r.getString("trace_id"),r.getString("decline_class"),r.getString("provider_code"),"true".equals(r.getString("failover_eligible")),r.getString("result_code")),args);
  }
  private PreparedAuth prepareAuth(String room, String key, Authorization request, String traceId, String flow) {
    var rows=authRows("SELECT * FROM meridian_authorizations WHERE room=? AND client_key=?",room,key);
    if(!rows.isEmpty()) {
      var old=rows.getFirst();
      if(!old.payload().equals(authPayload(request))) throw new ResponseStatusException(HttpStatus.CONFLICT,"Idempotency key belongs to a different payment");
      return new PreparedAuth(old,true);
    }
    var decision=ProviderRouter.route(request.corridor(),request.method());
    if(decision==null || !providers.containsKey(decision.providerId())) throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Unknown corridor");
    var state=read(room);
    if(state.getBalance()-reserved(room)<request.amountMinor()) throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Insufficient available balance");
    String id=UUID.randomUUID().toString();
    db.update("INSERT INTO meridian_authorizations(payment_id,room,client_key,payload,phase,provider,amount,corridor,trace_id,decline_class,provider_code,failover_eligible,result_code) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)",
      id,room,key,authPayload(request),"PROCESSING",decision.providerId(),request.amountMinor(),request.corridor(),traceId,"NONE","","false","");
    auditAuth(room,"sca.authenticated",id,decision.providerId(),traceId,Map.of("flow",flow,"status","AUTHENTICATED"));
    auditAuth(room,"routing.decided",id,decision.providerId(),traceId,Map.of("corridor",decision.corridor(),"reason",decision.reason(),"method",request.method(),"pairedProvider",decision.pairedProviderId(),"failoverAttempted",false));
    auditAuth(room,"auth.processing",id,decision.providerId(),traceId,Map.of("status","PROCESSING"));
    return new PreparedAuth(new AuthRow(id,room,key,authPayload(request),"PROCESSING",decision.providerId(),request.amountMinor(),request.corridor(),traceId,"NONE","",false,""),false);
  }
  private Map<String,Object> failChallenge(String room, String key, Authorization request, String traceId, String flow) {
    var rows=authRows("SELECT * FROM meridian_authorizations WHERE room=? AND client_key=?",room,key);
    if(!rows.isEmpty()) {
      var old=rows.getFirst();
      if(!old.payload().equals(authPayload(request))) throw new ResponseStatusException(HttpStatus.CONFLICT,"Idempotency key belongs to a different payment");
      return replayAuth(old);
    }
    String id=UUID.randomUUID().toString();
    db.update("INSERT INTO meridian_authorizations(payment_id,room,client_key,payload,phase,provider,amount,corridor,trace_id,decline_class,provider_code,failover_eligible,result_code) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)",
      id,room,key,authPayload(request),"FAILED","",request.amountMinor(),request.corridor(),traceId,"HARD","","false","SCA_CHALLENGE_FAILED");
    auditAuth(room,"sca.challenge_failed",id,"",traceId,Map.of("flow",flow,"status","FAILED"));
    auditAuth(room,"auth.failed",id,"",traceId,Map.of("status","FAILED","declineClass","HARD","failoverEligible",false,"failoverAttempted",false,"reason","sca_challenge_failed"));
    return authDecline(new AuthRow(id,room,key,authPayload(request),"FAILED","",request.amountMinor(),request.corridor(),traceId,"HARD","",false,"SCA_CHALLENGE_FAILED"),"SCA_CHALLENGE_FAILED","Step-up challenge failed. No authorization was sent.");
  }
  private Map<String,Object> finishAuth(AuthRow row, Authorization request, SandboxAuthorization outcome) {
    var decision=ProviderRouter.route(request.corridor(),request.method());
    String paired=decision==null?"":decision.pairedProviderId();
    return switch(outcome.outcome()) {
      case "SETTLED" -> {
        var txn=appendCompleted(row.room(),row.id(),row.provider(),row.amount(),request.recipientId(),request.method(),request.note());
        db.update("UPDATE meridian_authorizations SET phase='SUCCEEDED', decline_class='NONE', provider_code=?, failover_eligible='false', result_code='AUTHORIZED' WHERE payment_id=?",outcome.providerCode(),row.id());
        auditAuth(row.room(),"auth.succeeded",row.id(),row.provider(),row.traceId(),Map.of("status","SUCCEEDED","providerCode",outcome.providerCode(),"declineClass","NONE","failoverEligible",false,"failoverAttempted",false));
        yield authSuccess(row,outcome.providerCode(),txn);
      }
      case "SOFT_DECLINE" -> {
        db.update("UPDATE meridian_authorizations SET phase='FAILED', decline_class='SOFT', provider_code=?, failover_eligible='true', result_code='SOFT_DECLINE' WHERE payment_id=?",outcome.providerCode(),row.id());
        auditAuth(row.room(),"auth.failed",row.id(),row.provider(),row.traceId(),Map.of("status","FAILED","providerCode",outcome.providerCode(),"declineClass","SOFT","failoverEligible",true,"failoverAttempted",false));
        auditAuth(row.room(),"routing.failover_withheld",row.id(),row.provider(),row.traceId(),Map.of("reason","rehearsal_does_not_dispatch_second_provider","pairedProvider",paired,"failoverEligible",true,"failoverAttempted",false));
        yield authDecline(new AuthRow(row.id(),row.room(),row.key(),row.payload(),"FAILED",row.provider(),row.amount(),row.corridor(),row.traceId(),"SOFT",outcome.providerCode(),true,"SOFT_DECLINE"),"SOFT_DECLINE","Sandbox soft decline. No debit was made. Failover was not attempted.");
      }
      case "HARD_DECLINE" -> {
        db.update("UPDATE meridian_authorizations SET phase='FAILED', decline_class='HARD', provider_code=?, failover_eligible='false', result_code='HARD_DECLINE' WHERE payment_id=?",outcome.providerCode(),row.id());
        auditAuth(row.room(),"auth.failed",row.id(),row.provider(),row.traceId(),Map.of("status","FAILED","providerCode",outcome.providerCode(),"declineClass","HARD","failoverEligible",false,"failoverAttempted",false));
        yield authDecline(new AuthRow(row.id(),row.room(),row.key(),row.payload(),"FAILED",row.provider(),row.amount(),row.corridor(),row.traceId(),"HARD",outcome.providerCode(),false,"HARD_DECLINE"),"HARD_DECLINE","Sandbox hard decline. Terminal. No debit was made.");
      }
      default -> {
        db.update("UPDATE meridian_authorizations SET phase='PROCESSING', decline_class='NONE', provider_code='AMBIGUOUS', failover_eligible='false', result_code='AUTHORIZATION_AMBIGUOUS' WHERE payment_id=?",row.id());
        auditAuth(row.room(),"auth.ambiguous",row.id(),row.provider(),row.traceId(),Map.of("status","PROCESSING","reason","ambiguous_outcome_no_fallback","failoverEligible",false,"failoverAttempted",false));
        yield authAmbiguous(new AuthRow(row.id(),row.room(),row.key(),row.payload(),"PROCESSING",row.provider(),row.amount(),row.corridor(),row.traceId(),"NONE","AMBIGUOUS",false,"AUTHORIZATION_AMBIGUOUS"));
      }
    };
  }
  private Map<String,Object> replayAuth(AuthRow row) {
    String code=row.resultCode()==null?"":row.resultCode();
    return switch(code) {
      case "AUTHORIZED" -> {
        var state=read(row.room());
        var txn=state.getTransactions().stream().filter(t->t.getId().equals(row.id())).findFirst().orElseThrow();
        yield authSuccess(row,row.providerCode(),txn);
      }
      case "SOFT_DECLINE" -> authDecline(row,"SOFT_DECLINE","Sandbox soft decline. No debit was made. Failover was not attempted.");
      case "HARD_DECLINE" -> authDecline(row,"HARD_DECLINE","Sandbox hard decline. Terminal. No debit was made.");
      case "SCA_CHALLENGE_FAILED" -> authDecline(row,"SCA_CHALLENGE_FAILED","Step-up challenge failed. No authorization was sent.");
      default -> authAmbiguous(row);
    };
  }
  private Map<String,Object> authSuccess(AuthRow row, String providerCode, Transaction txn) {
    var body=authBase(true,"SUCCEEDED","AUTHORIZED",row);
    body.put("declineClass","NONE");
    body.put("failoverEligible",false);
    body.put("failoverAttempted",false);
    body.put("providerCode",providerCode==null?"":providerCode);
    body.put("state",read(row.room()));
    body.put("transaction",txn);
    return body;
  }
  private Map<String,Object> authDecline(AuthRow row, String code, String error) {
    var body=authBase(false,"FAILED",code,row);
    body.put("error",error);
    body.put("declineClass",row.declineClass());
    body.put("failoverEligible",row.failoverEligible());
    body.put("failoverAttempted",false);
    body.put("providerCode",row.providerCode()==null?"":row.providerCode());
    return body;
  }
  private Map<String,Object> authAmbiguous(AuthRow row) {
    var body=authBase(false,"PROCESSING","AUTHORIZATION_AMBIGUOUS",row);
    body.put("error","Authorization outcome is ambiguous. No debit was made and no provider fallback was attempted. Replay the same Idempotency-Key; do not start another payment.");
    body.put("declineClass","NONE");
    body.put("failoverEligible",false);
    body.put("failoverAttempted",false);
    body.put("providerCode","AMBIGUOUS");
    return body;
  }
  private Map<String,Object> scaRejected(String code, String error, String traceId) {
    var body=new LinkedHashMap<String,Object>();
    body.put("ok",false); body.put("code",code); body.put("error",error); body.put("traceId",traceId); body.put("simulation",true);
    return body;
  }
  private Map<String,Object> authBase(boolean ok, String status, String code, AuthRow row) {
    var body=new LinkedHashMap<String,Object>();
    body.put("ok",ok);
    body.put("status",status);
    body.put("code",code);
    body.put("traceId",row.traceId());
    body.put("paymentId",row.id());
    body.put("provider",row.provider()==null?"":row.provider());
    body.put("corridor",row.corridor());
    body.put("simulation",true);
    return body;
  }
}
